controllers:
    resource: ../src/Controller/
    type: attribute

lucky:
    path: /lucky
    controller: App\Controller\LuckyController::number
product:
    path: /products
    controller: App\Controller\interfasy::list

session:
    path: /session
    controller: App\Controller\SsController::session

email:
    path: /email
    controller: App\Controller\MailController::sendEmail
