controllers:
    resource: ../src/Controller/
    type: attribute

lucky:
    path: /lucky
    controller: App\Controller\LuckyController::number
product:
    path: /products
    controller: App\Controller\interfasy::list